### ISSUE TITLE
Generated thumbnails are missing code text

### ISSUE THREAD

**Issue by wojtekmaj** [biomejs/website#1091]
### Documentation URL

https://biomejs.dev/linter/rules/use-flat-map/

### Description

The text in `these quotes` is missing on thumbnails:

![image](https://github.com/user-attachments/assets/870c4a09-ffbf-4458-a022-6176e4cd46fe)

### Expectations

Text to appear on thumbnails.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by nhedger** [comment]
The OG image generated does not have an issue rendering the text and matches what's inside the file. However, the text inside the file is already incorrect. It looks like the generation step fails to include the quoted text.
