### ISSUE TITLE
Two typos in "Biome v1.9 Anniversary Release" post

### ISSUE THREAD

**Issue by joshlawton** [biomejs/website#1101]
Today's version 1.9 blog post contains two typos:

* reelase = release
* amd = and

https://biomejs.dev/blog/

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/c5396d7e-88f0-48fa-be5b-e6fc3743ae4d">
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/adc93c90-5f21-4151-ab7d-505c0ddcaa05">

**Comment by Conaclos** [comment]
Thanks! This is fixed :)
