### ISSUE TITLE
📚 `useEditorconfig` is not documented in Configuration reference

### ISSUE THREAD

**Issue by Conaclos** [biomejs/website#1230]
### Documentation URL

https://biomejs.dev/reference/configuration/

### Description

[`formatter.useEditorconfig`](https://github.com/biomejs/biome/blob/main/CHANGELOG.md#configuration-1) is not documented.

We should also update the [formatter introduction](https://biomejs.dev/formatter/#options) (`Biome doesn’t support .editorconfig yet.`)

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
@dyc3 are you interested?

**Comment by dyc3** [comment]
Sure, I can fix this.
