### ISSUE TITLE
RSS not working

### ISSUE THREAD

**Issue by developomp** [biomejs/website#1581]
The RSS feed linked in the navbar and in the sidebar of [Blog](https://biomejs.dev/blog/) page returns a 404 Not Found error.

**Comment by ematipico** [comment]
Seems like an upstream bug 

https://github.com/HiDeoo/starlight-blog/issues/107

**Comment by developomp** [comment]
bug was reintroduced in 14d75051f3a63805670790d694ad28e717374801
