### ISSUE TITLE
Playwright Tests / test (pull_request) failing at build step (uncommitted changes to tracked files when running Lunaria)

### ISSUE THREAD

**Issue by webdevbynight** [biomejs/website#1597]
Hello, everyone,

I have been facing the following failure for 5 days (since I opened PR #1574) when creating a PR to submit the translation of a MDX file or when a PR is updated with a new comment (e.g.: PR #1556 having this failure today): the Github Action called “Playwright Tests” fails at the “Build” step, after the Vite client is built, with the following error message:
>  generating static routes 
> <time> ▶ @astrojs/starlight/routes/static/404.astro
> <time>   └─ /404.html (+33ms)
> <time> ▶ @lunariajs/starlight/src/components/Dashboard.astro
> [error] Failed to retrieve last commit data from /home/runner/work/website/website/src/content/docs/fr/[the remaining path to the MDX file submitted by the PR]. Your working copy should not contain uncommitted changes to tracked files when running Lunaria. This might also happen when developing locally on a monorepo without the repository.rootDir option set.

What I do not understand is, when I push the branch I use as the source for the PR I open, the only tracked file in the branch is the MDX one and I do not see any uncommitted changes. Unless I have done something wrong when syncing my fork and pulling it into my local copy…

When trying to build locally, running `pnpm build`, I do not reproduce such a failure.

Should I be worried about such a failure? Or does it have no impact on the stuff I am doing to translate the documentation?

**Comment by dyc3** [comment]
This is a thing for us to worry about. I'm getting the same behavior on my machine.

**Comment by ematipico** [comment]
I fixed this here: https://github.com/biomejs/website/pull/1584

It's possible your upstream isn't up to date

**Comment by ematipico** [comment]
This is now fixed :) you just need to merge `main` into your PRs, and they should become green again
