### ISSUE TITLE
📚 Website seems to be down for a long time

### ISSUE THREAD

**Issue by himaanshu24** [biomejs/website#32]
### Documentation URL

https://biomejs.dev/

### Description

Not able to access the site/documentation. This happened earlier also, but got resolved. Now it has been down for quite some time and we are not able to access any documentation.

<img width="823" alt="image" src="https://github.com/biomejs/website/assets/8476966/01d2d67f-9760-4131-b96e-388278c4e86e">

<img width="1101" alt="image" src="https://github.com/biomejs/website/assets/8476966/d8cfc6ad-f248-4735-9b02-fcdf7659e97f">

### Expectations

We should be able to access the website securely.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
This might be an issue of your network. https://www.sslshopper.com/ssl-checker.html?host=biomejs.dev#hostname=biomejs.dev

**Comment by himaanshu24** [comment]
Hi @Sec-ant / @ematipico, Can you please look into the error on Firefox as well? I do not have any issues on any other website except this one. Maybe there is some nuance?

<img width="1003" alt="image" src="https://github.com/biomejs/website/assets/8476966/6272768c-5a73-4d8c-b506-e1549d9d3eba">

**Comment by Sec-ant** [comment]
We cannot reproduce the issue you're experiencing, so we don't know what error we should look into:

![image](https://github.com/biomejs/website/assets/10386119/6ee757ce-3d55-4059-9f34-6e2538feb86a)

![image](https://github.com/biomejs/website/assets/10386119/2cf2df80-acbe-4c1b-a0d2-862f5ac30930)

Can you try accessing the website from another network access point?

**Comment by himaanshu24** [comment]
Thank you @Sec-ant for your quick reply and your time. I will try to figure out what the issue is.

**Comment by ematipico** [comment]
@himaanshu24 where are you connecting from? Did you check if Netlify has issues from your country? Have you tried a VPN?
