### ISSUE TITLE
noImplicitBoolean does the opposite than linked ESLint rule

### ISSUE THREAD

**Issue by chekrd** [biomejs/website#341]
### Documentation URL

https://biomejs.dev/linter/rules/no-implicit-boolean/

### Description

Biome [lint/style/noImplicitBoolean](https://biomejs.dev/linter/rules/no-implicit-boolean/) does the opposite of the default [react/jsx-boolean-value](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md).

Current "Same as: react/jsx-boolean-value" is misleading as the default behavior of the ESLint rule is about removing the implicit values and lint/style/noImplicitBoolean has no way to achieve it.

### Expectations

Do not say it is "same as".

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Thank you!
