### ISSUE TITLE
noDangerouslySetInnerHtml and noDangerouslySetInnerHtmlWithChildren links wrong ESLint rules

### ISSUE THREAD

**Issue by chekrd** [biomejs/website#342]
### Documentation URL

https://biomejs.dev/linter/rules/no-dangerously-set-inner-html
https://biomejs.dev/linter/rules/no-dangerously-set-inner-html-with-children

### Description

Those two have switched the ESLint rule they refer to. It should say that rule [lint/security/noDangerouslySetInnerHtml](https://biomejs.dev/linter/rules/no-dangerously-set-inner-html/) is the same as [react/no-danger](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-danger.md), and rule [lint/security/noDangerouslySetInnerHtmlWithChildren](https://biomejs.dev/linter/rules/no-dangerously-set-inner-html-with-children/) is the same as [react/no-danger-with-children](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-danger-with-children.md)

### Expectations

Lint descriptions match the ESLint rules.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
Reopened in the main repo: https://github.com/biomejs/biome/issues/2854
