### ISSUE TITLE
noDebugger Rule Documentation Links to Localhost Instead of Relative Path

### ISSUE THREAD

**Issue by roadsidev** [biomejs/website#415]
### Documentation URL

https://biomejs.dev/linter/#rules

### Description

The documentation page for the **noDebugger** rule currently links to a local development environment URL. This link should be relative instead of absolute

Wrong link: http://localhost:4321/linter/rules/no-debugger

### Expectations

The link in the **Linter** Rules documentation should be a relative path, ensuring it is functional regardless of the environment in which the documentation is viewed.

Expected link: https://biomejs.dev/linter/rules/no-debugger/

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
That's easy to fix, PR welcome

**Comment by roadsidev** [comment]
I sent the PR #418 ! Thank you
