### ISSUE TITLE
🐛 `biome` ignores shared biome config in git hook commands in monorepo

### ISSUE THREAD

**Issue by sbsrnt** [biomejs/website#47]
Edit: Referencing this issue for visibility in biomejs/biome#2228 in order to help track down any related issues should this be resolved/supported.

---

### Environment information

```block
CLI:
  Version:                      1.6.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.1.0"

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

It's a little bit hard to replicate my setup with the playground links due to the shared config package and `ci` nature.

Example run in ci: https://github.com/exile-watch/nucleus/actions/runs/8441346324/job/23120305017#step:2:252

Here is the shared config: https://github.com/exile-watch/splinters/blob/main/packages/biome-config/biome.json#L30-L34

Here is how it's utilized: https://github.com/exile-watch/nucleus/blob/main/packages/encounter-data/biome.json

And here is a package json that has tabs instead of spaces: https://github.com/exile-watch/nucleus/blob/main/packages/encounter-data/package.json

---

Locally everything is passing when i go with `npm run format` or `npm run lint` but for some reason the `ci` command fails

---
Another potential issue I've noticed, though this one is with pre-commit git hooks, is that the recipe command in biomejs.dev site is resetting any `format`/`lint --apply` changes (which also gives an indication of somewhat ignoring _some_ rules from shared config)

```
pre-commit:
  commands:
    check:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
      run: npx biome check --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
``` 
this one in particular, but I can "easily" bypass that by changing the run script to `npm run lint` so it can respect my shared config 

### Expected result

I wouldn't expect indent errors to appear in `ci`.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by itsvetkov-wyn** [comment]
Workaround _(that worked for me at least)_ is to create another `biome.json` at the root (where `lefthook.yaml` is located) and configure it so:

```json
{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "extends": ["./path/to/your/biome.json"]
}
```

This fixed my issue of running `npx @biomejs/biome check ...` not respecting my _actual_ configuration.
