### ISSUE TITLE
process.exit() inside switch/case gives invalid `lint/suspicious/noFallthroughSwitchClause` - conflicting with TypeScript

### ISSUE THREAD

**Issue by gregbacchus** [biomejs/website#49]
### Environment information

e.g.

```typescript
switch (getStringProperty(error, 'code')) {
  case 'EACCES':
    console.error(`${bind} requires elevated privileges`);
    process.exit(EXIT_ERROR);
  case 'EADDRINUSE':
    console.error(`${bind} is already in use`);
    process.exit(EXIT_ERROR);
  default:
    throw error;
}
```

Gives error

```
error.ts:86:7 lint/suspicious/noFallthroughSwitchClause ━━━━━━━━━━

  ✖ This case is falling through to the next case.
  
    84 │     // handle specific listen errors with friendly messages
    85 │     switch (getStringProperty(error, 'code')) {
  > 86 │       case 'EACCES':
       │       ^^^^^^^^^^^^^^
  > 87 │         console.error(`${bind} requires elevated privileges`);
  > 88 │         process.exit(EXIT_ERROR);
       │         ^^^^^^^^^^^^^^^^^^^^^^^^^
    89 │       case 'EADDRINUSE':
    90 │         console.error(`${bind} is already in use`);
  
  ℹ Add a `break` or `return` statement to the end of this case to prevent fallthrough.
```

However, adding a return or break gives a typescript error saying unreachable code detected.

### Rule name

lint/suspicious/noFallthroughSwitchClause

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&importSortingEnabled=false&code=cwB3AGkAdABjAGgAIAAoAGcAZQB0AFMAdAByAGkAbgBnAFAAcgBvAHAAZQByAHQAeQAoAGUAcgByAG8AcgAsACAAJwBjAG8AZABlACcAKQApACAAewAKACAAIABjAGEAcwBlACAAJwBFAEEAQwBDAEUAUwAnADoACgAgACAAIAAgAGMAbwBuAHMAbwBsAGUALgBlAHIAcgBvAHIAKABgACQAewBiAGkAbgBkAH0AIAByAGUAcQB1AGkAcgBlAHMAIABlAGwAZQB2AGEAdABlAGQAIABwAHIAaQB2AGkAbABlAGcAZQBzAGAAKQA7AAoAIAAgACAAIABwAHIAbwBjAGUAcwBzAC4AZQB4AGkAdAAoAEUAWABJAFQAXwBFAFIAUgBPAFIAKQA7AAoAIAAgAGMAYQBzAGUAIAAnAEUAQQBEAEQAUgBJAE4AVQBTAEUAJwA6AAoAIAAgACAAIABjAG8AbgBzAG8AbABlAC4AZQByAHIAbwByACgAYAAkAHsAYgBpAG4AZAB9ACAAaQBzACAAYQBsAHIAZQBhAGQAeQAgAGkAbgAgAHUAcwBlAGAAKQA7AAoAIAAgACAAIABwAHIAbwBjAGUAcwBzAC4AZQB4AGkAdAAoAEUAWABJAFQAXwBFAFIAUgBPAFIAKQA7AAoAIAAgAGQAZQBmAGEAdQBsAHQAOgAKACAAIAAgACAAdABoAHIAbwB3ACAAZQByAHIAbwByADsACgB9AA%3D%3D

### Expected result

It should not display an error

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by lgarron** [comment]
> I would argue that this is a Node.js thing, and `process.exit` is a side effect that the rule shouldn't handle.

Is this something that could be revisited now?
