### ISSUE TITLE
📎 Prettier in the Playground recognizes JSON as JavaScript

### ISSUE THREAD

**Issue by Conaclos** [biomejs/website#53]
### Description

In the Playground we can add a JSON file. Biome correctly recognized it as JSON and format this as a JSON file. Prettier seems to recognize the file as JavaScript, because it removes the quotes around the property.

See this [Playground example](https://biomejs.dev/playground/?files.test.json=ewAKACAAIAAiAHAAcgBvAHAAIgA6ACAAdAByAHUAZQAKAH0A).

The Playground should correctly inform Prettier than the file is a JSON file.

**Comment by Conaclos** [comment]
Note: I had to create the issue on the main repo, because the website repo has a single issue template for docs

**Comment by nhedger** [comment]
> Note: I had to create the issue on the main repo, because the website repo has a single issue template for docs

You can open arbitrary issues with this link
<img width="1227" alt="Screenshot 2024-04-17 at 18 35 09" src="https://github.com/biomejs/website/assets/649677/618bf87b-d2af-403d-876c-ad7fed3ad8e2">
