### ISSUE TITLE
📚 Allow users to collapse the left-hand sidebar with their mouse or a keyboard shortcut

### ISSUE THREAD

**Issue by hamirmahal** [biomejs/website#676]
### Documentation URL

https://biomejs.dev/guides/getting-started/

### Description

The docs page looks a bit cluttered in portrait mode.

### Expectations

It'd be nice if users could collapse the left-hand sidebar.

A keyboard shortcut like Ctrl + Shift + S to toggle the left-hand sidebar would be a nice feature, too.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by hamirmahal** [comment]
![image](https://github.com/biomejs/website/assets/43425812/cbef9bd2-8a48-49df-906c-ad4859b807d4)

**Comment by ematipico** [comment]
I think I didn't understand what you were asking. Can't you click the arrows to collapse the drop-downs?

**Comment by hamirmahal** [comment]
The arrows can collapse individual sections, sure, but it'd be nice if users could toggle the entire sidebar, maybe with a user-customizable keyboard shortcut like `Ctrl` + `Shift` + `S`.

**Comment by hamirmahal** [comment]
https://rustwasm.github.io/docs/book/game-of-life/hello-world.html#whats-inside has this collapsible sidebar behavior.

[Screencast from 07-06-2024 04:12:16 PM.webm](https://github.com/biomejs/website/assets/43425812/55ea3399-2ab4-43be-9b1b-33d04a8b69a0)

**Comment by ematipico** [comment]
Closing for now, I shared your proposal to starlight
