### ISSUE TITLE
📚 Linter rules properties: I can't remember the icon labels

### ISSUE THREAD

**Issue by xnuk** [biomejs/website#679]
### Documentation URL

https://biomejs.dev/linter/rules/

### Description

At the very top of the page, it explains what each icon means what:

> Below the list of rules supported by Biome, divided by group. Here’s a legend of the emojis:
> - The icon ![check icon] indicates that the rule is part of the recommended rules.
> - The icon ![gear icon] indicates that the rule provides a code action (fix) that is **safe** to apply.
> - The icon ![warning icon] indicates that the rule provides a code action (fix) that is **unsafe** to apply.
> - The icon ![JS icon] indicates that the rule is applied to JavaScript and super languages files.
> - The icon ![TS icon] indicates that the rule is applied to TypeScript and TSX files.
> - The icon ![brace icon] indicates that the rule is applied to JSON files.
> - The icon ![hash icon] indicates that the rule is applied to CSS files.

But this page is too long; scrolling little bit I forgot what ![gear icon] stands for, more scrolling I forgot what ![hash icon] stands for, and after the half of the doc only I can remember was ![JS icon] and ![TS icon]. There's no mouseover tooltip in icons, so I have to scroll back to the top.

[check icon]: https://github.com/biomejs/website/assets/3071003/6ad68891-0dab-4c06-91d8-81e362d0771e
[gear icon]: https://github.com/biomejs/website/assets/3071003/fc8f385a-bb6c-435a-9a33-99c3fd8cf40e
[warning icon]: https://github.com/biomejs/website/assets/3071003/0e555d55-1fe5-4a55-b8d6-97b31af22e4f
[JS icon]: https://github.com/biomejs/website/assets/3071003/7a01f31a-113e-484d-9b91-18bb780b56d4
[TS icon]: https://github.com/biomejs/website/assets/3071003/30146e1d-982c-4e11-a9b7-41e23c276961
[brace icon]: https://github.com/biomejs/website/assets/3071003/09f15055-5227-4d77-ac60-9272939f09a8
[hash icon]: https://github.com/biomejs/website/assets/3071003/cd2eaf30-3368-4827-a617-3f0f774aaae6

### Expectations

One could be a tooltip, like moving from existing `aria-label` to `title`:
```html
<span class="inline-icon" title="The rule has a safe fix" role="img">
  <Icon name="seti:config" />
</span>
```

Or one could be a text label instead of icons, for clear meaning. I think it can be short enough to label as a text.
```html
<td>
  <span class="badge">Recommended</span>
  <span class="badge">Safe fix</span>
  <span class="badge">CSS</span>
</td>
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Do you want to send a PR @xnuk ?

**Comment by xnuk** [comment]
No for now. I just wanted to add an idea and ask about which direction you prefer.

**Comment by ematipico** [comment]
I am more incline towards the first approach (which is very similar to the first version we have before having starlight)
