### ISSUE TITLE
Discord link on main website is invalid

### ISSUE THREAD

**Issue by MylesWritesCode** [biomejs/website#814]
### Documentation URL

https://biomejs.dev/

### Description

![image](https://github.com/user-attachments/assets/ed33ab8c-ae41-4350-a707-f24d0837259a)

The above link (https://discord.com/invite/BypW39g6Yc) opens in Discord, saying it's an invalid link

### Expectations

I expected to open Discord into the Biome server

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
I just checked, and that link is correct
