### ISSUE TITLE
📚 fix/typo-japanese-reference

### ISSUE THREAD

**Issue by nka21** [biomejs/website#920]
### Documentation URL

https://biomejs.dev/ja/reference/configuration/

### Description

miss typo `VSCクライアント`

path: `src/content/docs/ja/reference/configuration.mdx` Line 128

### Expectations

Correct typo `VCSクライアント`

path: `src/content/docs/ja/reference/configuration.mdx` Line 128

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Do you want to send a PR?

**Comment by nka21** [comment]
> Do you want to send a PR?

If possible, I would like to have a small amount of cooperation with this OSS
but if it is difficult, then please close this issue.

**Comment by nka21** [comment]
> If you go to the very bottom of the page, you'll see a link that allows you to modify the page in place, and you don't need to do anything else. You just need to change the incorrect phrase and submit the PR.
> 
> ![Screenshot 2024-08-12 at 11 26 47](https://private-user-images.githubusercontent.com/602478/357011921-fd08f973-8d4e-47f5-a222-fa96fd921266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NjY5NDAsIm5iZiI6MTcyMzQ2NjY0MCwicGF0aCI6Ii82MDI0NzgvMzU3MDExOTIxLWZkMDhmOTczLThkNGUtNDdmNS1hMjIyLWZhOTZmZDkyMTI2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxMjQ0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Nzg1NGZmNTg4YWIzNTE3NzUxMmZhMTY3ZjkwMTFjZmQ0MTNmNGZkNWQ2ZDM5MmFhNzhiNmZmYTNhMjhjYWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m4wsKQEdNqjhjED4q9KneTW_eXH1jpw5ZricUCGrcEI)

thanks! I sent it. #930
